framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
#        precompress:
#            # possible values: 'brotli', 'zstandard', 'gzip'
#            format: 'zstandard'
