survos_crawler:
    base_url: 'https://pokemon.wip/'
    user_class: App\Entity\User
    users:
#        - user@user.com
    max_depth : 3
    routes_to_ignore :
        - 'app_logout'
    paths_to_ignore:
        - '/pokemon/batch-delete'
